ALTER TABLE "game_metadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "games" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "suspects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "locations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "weapons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "motives" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "clues" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "results" ENABLE ROW LEVEL SECURITY;
